@startuml
participant Initiator
participant Acceptor
participant Notary
title ExampleFlow 1\n(IOU)

autonumber

note over Initiator : Generating transaction based on new IOU
note over Initiator : Verifying contract constraints.
note over Initiator : Signing transaction with private key
Initiator -> Acceptor : Sending proposed transaction to borrower for review
note over Acceptor : Receiving proposed transaction from lender
note over Acceptor : Verifying signatures and contract constraints
note over Acceptor : Signing proposed transaction with our private key
Acceptor -> Notary : Requesting signature by notary service
note over Notary : Sign transaction
Acceptor <- Notary: Receive signed transaction
...
note over Acceptor : Record transaction
Initiator <- Acceptor : Broadcasting transaction to participants
note over Initiator : Record transaction
@enduml